// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMemoryStats() {
  return window['go']['monitors']['RunAnalyze']['GetMemoryStats']();
}

export function Startup(arg1) {
  return window['go']['monitors']['RunAnalyze']['Startup'](arg1);
}
