// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {monitors} from '../models';
import {context} from '../models';

export function GetMemoryStats():Promise<monitors.MemoryStats>;

export function Startup(arg1:context.Context):Promise<void>;
