// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['update']['UpdaterService']['CheckForUpdates']();
}

export function GetMetadata() {
  return window['go']['update']['UpdaterService']['GetMetadata']();
}

export function ProcessUpdate(arg1) {
  return window['go']['update']['UpdaterService']['ProcessUpdate'](arg1);
}

export function Startup(arg1) {
  return window['go']['update']['UpdaterService']['Startup'](arg1);
}
