// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSourceHealth(arg1) {
  return window['go']['remote']['RemoteHandler']['CheckSourceHealth'](arg1);
}

export function ClearAllCache() {
  return window['go']['remote']['RemoteHandler']['ClearAllCache']();
}

export function DeleteRemote(arg1) {
  return window['go']['remote']['RemoteHandler']['DeleteRemote'](arg1);
}

export function DownloadRemoteAsset(arg1) {
  return window['go']['remote']['RemoteHandler']['DownloadRemoteAsset'](arg1);
}

export function FetchRemoteAssets(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['remote']['RemoteHandler']['FetchRemoteAssets'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function FinalizeAsset(arg1, arg2) {
  return window['go']['remote']['RemoteHandler']['FinalizeAsset'](arg1, arg2);
}

export function GetCachePath() {
  return window['go']['remote']['RemoteHandler']['GetCachePath']();
}

export function GetCacheSize() {
  return window['go']['remote']['RemoteHandler']['GetCacheSize']();
}

export function GetRemotes() {
  return window['go']['remote']['RemoteHandler']['GetRemotes']();
}

export function RemoveAssetCache(arg1, arg2) {
  return window['go']['remote']['RemoteHandler']['RemoveAssetCache'](arg1, arg2);
}

export function SaveRemote(arg1) {
  return window['go']['remote']['RemoteHandler']['SaveRemote'](arg1);
}

export function Startup(arg1) {
  return window['go']['remote']['RemoteHandler']['Startup'](arg1);
}
