// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {remote} from '../models';
import {common} from '../models';
import {context} from '../models';

export function CheckSourceHealth(arg1:string):Promise<boolean>;

export function ClearAllCache():Promise<void>;

export function DeleteRemote(arg1:string):Promise<void>;

export function DownloadRemoteAsset(arg1:remote.RemoteAsset):Promise<void>;

export function FetchRemoteAssets(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:Array<string>,arg8:Array<remote.MappingRule>):Promise<Array<remote.RemoteAsset>>;

export function FinalizeAsset(arg1:string,arg2:string):Promise<common.SpineMetadata>;

export function GetCacheFolder():Promise<string>;

export function GetCachePath():Promise<string>;

export function GetCacheSize():Promise<string>;

export function GetRemotes():Promise<Array<remote.RemoteSource>>;

export function RefreshSource(arg1:string,arg2:Array<string>):Promise<void>;

export function RemoveAssetCache(arg1:string,arg2:string):Promise<void>;

export function SaveRemote(arg1:remote.RemoteSource):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
