// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeFolder(arg1) {
  return window['go']['services']['CLIService']['AnalyzeFolder'](arg1);
}

export function BuildCLICommand(arg1, arg2, arg3) {
  return window['go']['services']['CLIService']['BuildCLICommand'](arg1, arg2, arg3);
}

export function GetConfigPath() {
  return window['go']['services']['CLIService']['GetConfigPath']();
}

export function LoadConfig() {
  return window['go']['services']['CLIService']['LoadConfig']();
}

export function OldQueueTasks(arg1) {
  return window['go']['services']['CLIService']['OldQueueTasks'](arg1);
}

export function QueueTasks(arg1) {
  return window['go']['services']['CLIService']['QueueTasks'](arg1);
}

export function ResetShortcuts() {
  return window['go']['services']['CLIService']['ResetShortcuts']();
}

export function SaveConfig(arg1) {
  return window['go']['services']['CLIService']['SaveConfig'](arg1);
}

export function SelectExportFolder() {
  return window['go']['services']['CLIService']['SelectExportFolder']();
}

export function SelectFolder() {
  return window['go']['services']['CLIService']['SelectFolder']();
}

export function Startup(arg1) {
  return window['go']['services']['CLIService']['Startup'](arg1);
}
