// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function AnalyzeFolder(arg1:string):Promise<services.FolderSummary>;

export function BuildCLICommand(arg1:services.ExtractionOptions,arg2:string,arg3:string):Promise<Array<string>>;

export function GetConfigPath():Promise<string>;

export function LoadConfig():Promise<services.Config>;

export function OldQueueTasks(arg1:services.ExtractionOptions):Promise<void>;

export function QueueTasks(arg1:services.ExtractionOptions):Promise<void>;

export function ResetShortcuts():Promise<services.Config>;

export function SaveConfig(arg1:services.Config):Promise<void>;

export function SelectExportFolder():Promise<string>;

export function SelectFolder():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
