// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportFromDialog() {
  return window['go']['common']['CubismCommons']['ImportFromDialog']();
}

export function ProcessLive2DAsset(arg1) {
  return window['go']['common']['CubismCommons']['ProcessLive2DAsset'](arg1);
}

export function Startup(arg1) {
  return window['go']['common']['CubismCommons']['Startup'](arg1);
}
