// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';
import {context} from '../models';

export function ImportFromDialog():Promise<void>;

export function ProcessLive2DAsset(arg1:string):Promise<common.Live2DMetadata>;

export function Startup(arg1:context.Context):Promise<void>;
