// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';
import {context} from '../models';

export function GroupFilesIntoAssets(arg1:Array<string>):Promise<Array<common.SpineMetadata>>;

export function ProcessSingleAsset(arg1:string):Promise<common.SpineMetadata>;

export function RecursiveImport():Promise<void>;

export function SelectFiles():Promise<Array<common.SpineMetadata>>;

export function SelectFolder():Promise<Array<common.SpineMetadata>>;

export function Startup(arg1:context.Context):Promise<void>;
