// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GroupFilesIntoAssets(arg1) {
  return window['go']['common']['SpineCommons']['GroupFilesIntoAssets'](arg1);
}

export function ProcessSingleAsset(arg1) {
  return window['go']['common']['SpineCommons']['ProcessSingleAsset'](arg1);
}

export function RecursiveImport() {
  return window['go']['common']['SpineCommons']['RecursiveImport']();
}

export function SelectFiles() {
  return window['go']['common']['SpineCommons']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['common']['SpineCommons']['SelectFolder']();
}

export function Startup(arg1) {
  return window['go']['common']['SpineCommons']['Startup'](arg1);
}
