// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GroupFilesIntoAssets(arg1) {
  return window['go']['common']['SpineCommons']['GroupFilesIntoAssets'](arg1);
}

export function ImportFromCache(arg1) {
  return window['go']['common']['SpineCommons']['ImportFromCache'](arg1);
}

export function ImportFromDialog() {
  return window['go']['common']['SpineCommons']['ImportFromDialog']();
}

export function ProcessSingleAsset(arg1) {
  return window['go']['common']['SpineCommons']['ProcessSingleAsset'](arg1);
}

export function RecursiveImport(arg1, arg2) {
  return window['go']['common']['SpineCommons']['RecursiveImport'](arg1, arg2);
}

export function SelectFiles() {
  return window['go']['common']['SpineCommons']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['common']['SpineCommons']['SelectFolder']();
}

export function Startup(arg1) {
  return window['go']['common']['SpineCommons']['Startup'](arg1);
}
