// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentPlatform() {
  return window['go']['main']['App']['CurrentPlatform']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function SetWindowColor(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetWindowColor'](arg1, arg2, arg3, arg4);
}
