// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentPlatform():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Platform():Promise<string>;

export function SetWindowColor(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;
